flowchart LR

P["Subscription Provider<br/>GlaDOS<br/>"]
S["Subscription URL"]
G["Proxy Client(GUI)<br/>Clash Verge/Other Variants<br/>"]
C["Core<br/>Mihomo<br/>"]
I["VPN,启动🚀"]

P --> S --> G --> C --> I
